@demografana_HostAddress = http://localhost:8080

POST {{demografana_HostAddress}}/orders
Content-Type: application/json

{
  "customerId": "customer-123",
  "items": [
    {
      "productId": "1234",
      "quantity": 12,
      "unitPrice": 100.0
    }
  ]
}
